---
  - name: Create some users
    user: name={{item.name}} comment="user" generate_ssh_key=yes ssh_key_bits=2048 state=present password={{item.password}} shell=/bin/bash
    with_items:
      - { name: 'ita', password: 'ita' }

  - name: Copy ssh keys to the user's .ssh directory
    copy: src={{item.key}} dest=/home/{{item.name}}/.ssh/authorized_keys mode=0700 owner={{item.name}} group={{item.name}}
    with_items:
      - { name: 'ita', key: 'ita.pub' }
